version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8082:8"0
        links:
            -   fpm
        volumes:
            - ./:/var/www/OlibraryAPI
        container_name: olibrary-api-nginx
    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - ./:/var/www/OlibraryAPI
        links:
            -   mysql
        container_name: olibrary-api-fpm
    mysql:
        image: mysql:5.7
        ports:
            -   "33062:3306"
        environment:
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
    npm:
      build:
        context: .
        dockerfile: docker/npm/Dockerfile
      container_name: olibrary-api-npm
      volumes:
        - ./:/var/www/OlibraryAPI
      entrypoint: [ 'npm' ]
