version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - 8082:80
        links:
            -   fpm
        volumes:
            - ./:/var/www/Olibrary
        container_name: olibrary-api-nginx
    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - ./:/var/www/Olibrary
        links:
            -   mysql
        container_name: olibrary-api-fpm
    mysql:
        ports:
            -   33062:3306
        environment:
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
        image: mysql:5.7
